def make_state():
	l = ['Alabama', 'Alaska', 'Arizona','Arkansas','California','Colorado','Connecticut',
	'Delaware','District of Columbia','Florida','Georgia','Hawaii','Idaho',
 'Illinois','Indiana','Iowa','Kansas','Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New England',
 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina','South Dakota',
 'Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming']
	return l

def make_cancer():
	l = ['All Cancer Sites Combined', 'Brain and Other Nervous System','Cervix','Colon and Rectum','Corpus and Uterus, NOS','Esophagus'
,'Female Breast','Hodgkin Lymphoma','Kaposi Sarcoma','Kidney and Renal Pelvis','Larynx',
'Leukemias','Liver and Intrahepatic Bile Duct','Lung and Bronchus','Melanomas of the Skin',
'Mesothelioma','Myeloma','Non-Hodgkin Lymphoma','Oral Cavity and Pharynx','Ovary','Pancreas',
'Prostate','Stomach','Testis','Thyroid','Urinary Bladder']
	return l

def make_race():
	l = ['All Races','Black','Hispanic','Asian/Pacific Islander','White','American Indian/Alaska Native']
	return l

def make_compound():
	l = ['2,4-D','ATRAZINE','CHLORPYRIFOS','GLYPHOSATE','METHYLIODIDE','SULFOXAFLOR']
	return l

def make_crop():
	l = ['total','corn','soybeans','wheat','cotton','vegetables_and_fruit','rice','orchards_and_grapes','alfalfa','pasture_and_hay','other_crops']
	return l


# 6-BENZYLADENINE
# ABAMECTIN
# ACEPHATE
# ACEQUINOCYL
# ACETAMIPRID
# ACETOCHLOR
# ACIBENZOLAR
# ACIFLUORFEN
# ALACHLOR
# ALDICARB
# ALLYL ISOTHIOCYANATE
# ALPHA CYPERMETHRIN
# ALUMINUM PHOSPHIDE
# AMECTOCTRADIN
# AMETRYN
# AMINOPYRALID
# AMITRAZ
# AMITROLE
# AMMONIUM SULFAMATE
# AMPELOMYCES QUISQUALIS
# ANILAZINE
# ARSENIC ACID
# ASPERGILLUS FLAVUS
# ASULAM
# ATRAZINE
# AUREOBASIDIUM PULLULANS
# AVIGLYCINE
# AZADIRACHTIN
# AZINPHOS-METHYL
# AZOXYSTROBIN
# BACILLUS AMYLOLIQUIFACIEN
# BACILLUS CEREUS
# BACILLUS FIRMUS
# BACILLUS PUMILIS
# BACILLUS SUBTILIS
# BACILLUS THURINGIENSIS
# BARBAN
# BARIUM POLYSULFIDE
# BENDIOCARB
# BENFLURALIN
# BENOMYL
# BENSULFURON
# BENSULIDE
# BENTAZONE
# BENZOVINDIFLUPYR
# BICYCLOPYRONE
# BIFENAZATE
# BIFENOX
# BIFENTHRIN
# BISPYRIBAC
# BLAD PROTEIN
# BORDEAUX MIXTURE
# BOSCALID
# BROMACIL
# BROMOXYNIL
# BUPROFEZIN
# BURKHOLDERIA CEPACIA
# BURKHOLDERIA SPP
# BUTRALIN
# BUTYLATE
# CALCIUM CHLORIDE
# CALCIUM POLYSULFIDE
# CAPTAFOL
# CAPTAN
# CARBARYL
# CARBOFURAN
# CARBOPHENOTHION
# CARBOXIN
# CARFENTRAZONE-ETHYL
# CHENOPODIUM AMBROSIOIDES
# CHINOMETHIONAT
# CHLORAMBEN
# CHLORANTRANILIPROLE
# CHLORDIMEFORM
# CHLORETHOXYFOS
# CHLORFENAPYR
# CHLORIDAZON
# CHLORIMURON
# CHLORMEQUAT
# CHLOROBENZILATE
# CHLORONEB
# CHLOROPICRIN
# CHLOROTHALONIL
# CHLOROXURON
# CHLORPROPHAM
# CHLORPYRIFOS
# CHLORSULFURON
# CHROMOBACTERIUM SUBTSUGAE
# CINNAMALDEHYDE
# CLETHODIM
# CLODINAFOP
# CLOFENTEZINE
# CLOMAZONE
# CLOPYRALID
# CLORANSULAM-METHYL
# CLOTHIANIDIN
# COLLECTOTRICHUM SPORES
# CONIOTHYRIUM MINITANS
# COPPER
# COPPER HYDROXIDE
# COPPER OCTANOATE
# COPPER OXYCHLORIDE
# COPPER OXYCHLORIDE S
# COPPER SULFATE
# COPPER SULFATE TRIBASIC
# CPPU
# CRYOLITE
# CUPROUS OXIDE
# CYANAMIDE
# CYANAZINE
# CYANTRANILIPROLE
# CYAZOFAMID
# CYCLANILIDE
# CYCLOATE
# CYDIA POMONELLA
# CYFLUFENAMID
# CYFLUMETOFEN
# CYFLUTHRIN
# CYHALOFOP
# CYHALOTHRIN-GAMMA
# CYHALOTHRIN-LAMBDA
# CYMOXANIL
# CYPERMETHRIN
# CYPROCONAZOLE
# CYPRODINIL
# CYROMAZINE
# CYTOKININ
# DALAPON
# DAMINOZIDE
# DAZOMET
# DCPA
# DECAN-1-OL
# DELTAMETHRIN
# DEMETON
# DESMEDIPHAM
# DIALLATE
# DIAZINON
# DICAMBA
# DICHLOBENIL
# DICHLONE
# DICHLOROPROPENE
# DICHLORPROP
# DICLOFOP
# DICLORAN
# DICLOSULAM
# DICOFOL
# DICROTOPHOS
# DIENOCHLOR
# DIETHATYL
# DIFENOCONAZOLE
# DIFENZOQUAT
# DIFLUBENZURON
# DIFLUFENZOPYR
# DIMETHENAMID
# DIMETHENAMID & DIMETHENAMID-P
# DIMETHENAMID-P
# DIMETHIPIN
# DIMETHOATE
# DIMETHOMORPH
# DIMETHYL ARSINIC ACID
# DIMETHYL DISULFIDE
# DINOCAP
# DINOSEB
# DINOTEFURAN
# DIPHENAMID
# DIQUAT
# DISULFOTON
# DITHIOPYR
# DIURON
# DNOC
# DODINE
# DSMA
# EMAMECTIN
# ENDOSULFAN
# ENDOTHAL
# EPN
# EPTC
# ESFENVALERATE
# ETHALFLURALIN
# ETHAMETSULFURON
# ETHEPHON
# ETHION
# ETHOFUMESATE
# ETHOPROPHOS
# ETOXAZOLE
# ETRIDIAZOLE
# FAMOXADONE
# FATTY ALCOHOLS
# FENAMIDONE
# FENAMIPHOS
# FENARIMOL
# FENAZAQUIN
# FENBUCONAZOLE
# FENBUTATIN OXIDE
# FENHEXAMID
# FENOXAPROP
# FENOXYCARB
# FENPROPATHRIN
# FENPYROXIMATE
# FENSULFOTHION
# FENTIN
# FENVALERATE
# FERBAM
# FIPRONIL
# FLAZASULFURON
# FLONICAMID
# FLORASULAM
# FLUAZIFOP
# FLUAZINAM
# FLUBENDIAMIDE
# FLUCARBAZONE
# FLUCHLORALIN
# FLUCYTHRINATE
# FLUDIOXONIL
# FLUFENACET
# FLUMETRALIN
# FLUMETSULAM
# FLUMICLORAC
# FLUMIOXAZIN
# FLUOMETURON
# FLUOPICOLIDE
# FLUOPYRAM
# FLUOXASTROBIN
# FLUPYRADIFURONE
# FLURIDONE
# FLUROXYPYR
# FLUSILAZOLE
# FLUTHIACET-METHYL
# FLUTOLANIL
# FLUTRIAFOL
# FLUVALINATE
# FLUVALINATE TAU
# FLUXAPYROXAD
# FOLPET
# FOMESAFEN
# FONOFOS
# FORAMSULFURON
# FORMETANATE
# FOSAMINE
# FOSETYL
# GALLEX
# GAMMA AMINOBUTYRIC ACID
# GARLIC JUICE
# GENTAMICIN SULFATE
# GIBBERELLIC ACID
# GLIOCLADIUM VIRENS
# GLUFOSINATE
# GLYPHOSATE
# HALOSULFURON
# HARPIN PROTEIN
# HEXAZINONE
# HEXYTHIAZOX
# HYDRAMETHYLNON
# HYDRATED LIME
# HYDROGEN PEROXIDE
# HYDROXYPROPANOIC ACID
# HYMEXAZOL
# IBA
# IMAZALIL
# IMAZAMETHABENZ
# IMAZAMOX
# IMAZAPIC
# IMAZAPYR
# IMAZAQUIN
# IMAZETHAPYR
# IMAZOSULFURON
# IMIDACLOPRID
# INDAZIFLAM
# INDOXACARB
# IODOSULFURON
# IPCONAZOLE
# IPRODIONE
# ISARIA FUMOSOROSEA
# ISAZOFOS
# ISOFENPHOS
# ISOFETAMID
# ISOPROPALIN
# ISOXABEN
# ISOXAFLUTOLE
# KAOLIN CLAY
# KASUGAMYCIN
# KINOPRENE
# KRESOXIM-METHYL
# L-GLUTAMIC ACID
# LACTOFEN
# LEAD ARSENATE
# LINDANE
# LINURON
# MALATHION
# MALEIC HYDRAZIDE
# MANCOZEB
# MANDIPROPAMID
# MANEB
# MCPA
# MCPB
# MECOPROP
# MEFENOXAM
# MEFLUIDIDE
# MEPIQUAT
# MESOSULFURON
# MESOTRIONE
# METALAXYL
# METALDEHYDE
# METAM
# METAM POTASSIUM
# METCONAZOLE
# METHAMIDOPHOS
# METHAZOLE
# METHIDATHION
# METHIOCARB
# METHOMYL
# METHOXYCHLOR
# METHOXYFENOZIDE
# METHYL BROMIDE
# METHYL ISOTHIOCYANATE
# METHYL PARATHION
# METHYLIODIDE
# METIRAM
# METOLACHLOR
# METOLACHLOR & METOLACHLOR-S
# METOLACHLOR-S
# METRAFENONE
# METRIBUZIN
# METSULFURON
# MEVINPHOS
# MOLINATE
# MONOCROTOPHOS
# MSMA
# MYCLOBUTANIL
# MYROTHECIUM VERRUCARIA
# NALED
# NAPHTHYLACETAMIDE
# NAPHTHYLACETIC ACID
# NAPROPAMIDE
# NAPTALAM
# NAPTHA
# NEEM OIL
# NICOSULFURON
# NORFLURAZON
# NORURON
# NOSEMA LOCUSTAE CANN
# NOVALURON
# ORTHOSULFAMURON
# ORYZALIN
# OXADIAZON
# OXAMYL
# OXATHIAPIPROLIN
# OXYDEMETON-METHYL
# OXYFLUORFEN
# OXYTETRACYCLINE
# PACLOBUTRAZOL
# PAECILOMYCES LILACINUS
# PARAQUAT
# PARATHION
# PEBULATE
# PELARGONIC ACID
# PENDIMETHALIN
# PENFLUFEN
# PENOXSULAM
# PENTHIOPYRAD
# PERMETHRIN
# PETROLEUM DISTILLATE
# PETROLEUM OIL
# PHENMEDIPHAM
# PHORATE
# PHOSALONE
# PHOSMET
# PHOSPHAMIDON
# PHOSPHORIC ACID
# PHYTOPHTHORA SPORES
# PICLORAM
# PICOXYSTROBIN
# PINOLENE
# PINOXADEN
# PIPERONYL BUTOXIDE
# PIRIMICARB
# POLYHEDROSIS VIRUS
# POLYOXORIM
# POTASSIUM BICARBONATE
# POTASSIUM CARBONATE
# POTASSIUM OLEATE
# POTASSIUM SILICATE
# PRIMISULFURON
# PRODIAMINE
# PROFENOFOS
# PROFLURALIN
# PROHEXADIONE
# PROMETON
# PROMETRYN
# PROPACHLOR
# PROPAMOCARB HCL
# PROPANIL
# PROPARGITE
# PROPAZINE
# PROPICONAZOLE
# PROPOXUR
# PROPOXYCARBAZONE
# PROPYZAMIDE
# PROSULFURON
# PROTHIOCONAZOLE
# PSEUDOMONAS FLUORESCENS
# PYMETROZINE
# PYRACLOSTROBIN
# PYRAFLUFEN ETHYL
# PYRASULFOTOLE
# PYRETHRINS
# PYRIDABEN
# PYRIDATE
# PYRIMETHANIL
# PYRIPROXYFEN
# PYRITHIOBAC-SODIUM
# PYROXASULFONE
# PYROXSULAM
# QUINCLORAC
# QUINOXYFEN
# QUINTOZENE
# QUIZALOFOP
# RESMETHRIN
# REYNOUTRIA SACHALINENSIS
# RIMSULFURON
# ROTENONE
# RYANODINE
# SABADILLA
# SAFLUFENACIL
# SEDAXANE
# SETHOXYDIM
# SILICATES
# SIMAZINE
# SODIUM ARSENITE
# SODIUM CHLORATE
# SODIUM METABORATE
# SPINETORAM
# SPINOSYN
# SPIRODICLOFEN
# SPIROMESIFEN
# SPIROTETRAMAT
# STEINERNEMA CARPOCAP
# STEINERNEMA RIOBRAVI
# STREPTOMYCES LYDICUS
# STREPTOMYCIN
# SUCROSE OCTANOATE
# SULFALLATE
# SULFCARBAMIDE
# SULFENTRAZONE
# SULFOMETURON
# SULFOSATE
# SULFOSULFURON
# SULFOXAFLOR
# SULFUR
# SULFURIC ACID
# SULPROFOS
# TCA
# TCMTB
# TEBUCONAZOLE
# TEBUFENOZIDE
# TEBUPIRIMPHOS
# TEBUTHIURON
# TEFLUTHRIN
# TEMBOTRIONE
# TEMEPHOS
# TERBACIL
# TERBUFOS
# TERBUTRYN
# TETRABOROHYDRATE
# TETRACONAZOLE
# TETRAOXOSULFATE
# TETRATHIOCARBONATE
# THIABENDAZOLE
# THIACLOPRID
# THIAMETHOXAM
# THIAZOPYR
# THIDIAZURON
# THIENCARBAZONE-METHYL
# THIFENSULFURON
# THIOBENCARB
# THIODICARB
# THIOPHANATE-METHYL
# THIRAM
# TOLFENPYRAD
# TOPRAMEZONE
# TRALKOXYDIM
# TRALOMETHRIN
# TRI-ALLATE
# TRIADIMEFON
# TRIADIMENOL
# TRIASULFURON
# TRIAZAMATE
# TRIBENURON METHYL
# TRIBUFOS
# TRICHLORFON
# TRICLOPYR
# TRIDIPHANE
# TRIFLOXYSTROBIN
# TRIFLOXYSULFURON
# TRIFLUMIZOLE
# TRIFLURALIN
# TRIFLUSULFURON
# TRIFORINE
# TRIMETHACARB
# TRINEXAPAC
# TRITICONAZOLE
# UNICONAZOLE
# VERNOLATE
# VINCLOZOLIN
# ZETA-CYPERMETHRIN
# ZINC
# ZINEB
# ZIRAM
# ZOXAMIDE]
